<a href="https://colab.research.google.com/github/ARYAPRAGATHI7/arya_labs_and_projects/blob/main/my_first_colab_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

hi all
today is frist day to use colad

In [ ]:
import numpy as np;

In [ ]:
a=[1,2,3,3]
b=[2,3,4,5]

In [ ]:
c=np.array(a)
c1=np.array(b)

In [ ]:
#addition
print(c+c1)
#subtraction
print(c-c1)
#scalar multi
print(c*c1)
#dot produt
print(np.dot(a,b))
#length
print(np.linalg.norm(a))

[3 5 7 8]
[-1 -1 -1 -2]
[ 2  6 12 15]
35
4.795831523312719


In [ ]:
c+c1


array([3, 5, 7, 8])